version: '3'

services:
  db:
    image: postgres:13.1-alpine
    env_file: .env.dev
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  web:
    image: simbirsoft_spring2020test
    build:
      context: django_app/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env.dev
    volumes:
      - ./django_app/:/usr/src/app/
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

volumes:
  postgres_volume: